# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 501)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app_icon/shelf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAddGame = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddGame.sizePolicy().hasHeightForWidth())
        self.pushButtonAddGame.setSizePolicy(sizePolicy)
        self.pushButtonAddGame.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonAddGame.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonAddGame.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddGame.setIcon(icon1)
        self.pushButtonAddGame.setObjectName("pushButtonAddGame")
        self.horizontalLayout.addWidget(self.pushButtonAddGame)
        self.pushButtonRemoveGame = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemoveGame.sizePolicy().hasHeightForWidth())
        self.pushButtonRemoveGame.setSizePolicy(sizePolicy)
        self.pushButtonRemoveGame.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonRemoveGame.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonRemoveGame.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRemoveGame.setIcon(icon2)
        self.pushButtonRemoveGame.setObjectName("pushButtonRemoveGame")
        self.horizontalLayout.addWidget(self.pushButtonRemoveGame)
        self.pushButtonLoadBacklog = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLoadBacklog.sizePolicy().hasHeightForWidth())
        self.pushButtonLoadBacklog.setSizePolicy(sizePolicy)
        self.pushButtonLoadBacklog.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonLoadBacklog.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonLoadBacklog.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLoadBacklog.setIcon(icon3)
        self.pushButtonLoadBacklog.setObjectName("pushButtonLoadBacklog")
        self.horizontalLayout.addWidget(self.pushButtonLoadBacklog)
        self.pushButtonSaveBacklog = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSaveBacklog.sizePolicy().hasHeightForWidth())
        self.pushButtonSaveBacklog.setSizePolicy(sizePolicy)
        self.pushButtonSaveBacklog.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonSaveBacklog.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonSaveBacklog.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSaveBacklog.setIcon(icon4)
        self.pushButtonSaveBacklog.setObjectName("pushButtonSaveBacklog")
        self.horizontalLayout.addWidget(self.pushButtonSaveBacklog)
        self.pushButtonReloadScores = QtWidgets.QPushButton(MainWindow)
        self.pushButtonReloadScores.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReloadScores.sizePolicy().hasHeightForWidth())
        self.pushButtonReloadScores.setSizePolicy(sizePolicy)
        self.pushButtonReloadScores.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonReloadScores.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonReloadScores.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonReloadScores.setIcon(icon5)
        self.pushButtonReloadScores.setObjectName("pushButtonReloadScores")
        self.horizontalLayout.addWidget(self.pushButtonReloadScores)
        self.pushButtonSortData = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSortData.sizePolicy().hasHeightForWidth())
        self.pushButtonSortData.setSizePolicy(sizePolicy)
        self.pushButtonSortData.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonSortData.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonSortData.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSortData.setIcon(icon6)
        self.pushButtonSortData.setCheckable(True)
        self.pushButtonSortData.setChecked(False)
        self.pushButtonSortData.setObjectName("pushButtonSortData")
        self.horizontalLayout.addWidget(self.pushButtonSortData)
        self.pushButtonStatistics = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStatistics.sizePolicy().hasHeightForWidth())
        self.pushButtonStatistics.setSizePolicy(sizePolicy)
        self.pushButtonStatistics.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonStatistics.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonStatistics.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStatistics.setIcon(icon7)
        self.pushButtonStatistics.setObjectName("pushButtonStatistics")
        self.horizontalLayout.addWidget(self.pushButtonStatistics)
        self.pushButtonFilterData = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilterData.sizePolicy().hasHeightForWidth())
        self.pushButtonFilterData.setSizePolicy(sizePolicy)
        self.pushButtonFilterData.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButtonFilterData.setMaximumSize(QtCore.QSize(31, 31))
        self.pushButtonFilterData.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFilterData.setIcon(icon8)
        self.pushButtonFilterData.setCheckable(True)
        self.pushButtonFilterData.setObjectName("pushButtonFilterData")
        self.horizontalLayout.addWidget(self.pushButtonFilterData)
        self.label = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(46, 13))
        self.label.setMaximumSize(QtCore.QSize(46, 13))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditSearchGame = QtWidgets.QLineEdit(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSearchGame.sizePolicy().hasHeightForWidth())
        self.lineEditSearchGame.setSizePolicy(sizePolicy)
        self.lineEditSearchGame.setMinimumSize(QtCore.QSize(201, 20))
        self.lineEditSearchGame.setMaximumSize(QtCore.QSize(201, 20))
        self.lineEditSearchGame.setObjectName("lineEditSearchGame")
        self.horizontalLayout.addWidget(self.lineEditSearchGame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table = Table(MainWindow)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.pushButtonAddGame.setToolTip(_translate("MainWindow", "Add game/s"))
        self.pushButtonRemoveGame.setToolTip(_translate("MainWindow", "Delete game/s"))
        self.pushButtonLoadBacklog.setToolTip(_translate("MainWindow", "Load backlog"))
        self.pushButtonSaveBacklog.setToolTip(_translate("MainWindow", "Save backlog"))
        self.pushButtonReloadScores.setToolTip(_translate("MainWindow", "Reload scores"))
        self.pushButtonSortData.setToolTip(_translate("MainWindow", "Sort games"))
        self.pushButtonStatistics.setToolTip(_translate("MainWindow", "Statistics"))
        self.pushButtonFilterData.setToolTip(_translate("MainWindow", "Filter games"))
        self.label.setText(_translate("MainWindow", "Search:"))

from table import Table
import views.app_icon_rc
import views.main_window_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

